version: "3.0"
services:
  mmcc:
    image: giubots/mmcc
    volumes:
     - ./demo/config:/usr/src/mmcc/config
    ports:
    - 8765:8765
  rasa:
    image: rasa/rasa:2.2.6-full
    ports:
      - 5005:5005
    volumes:
      - ./demo/rasa:/app
    command: >
      run
      --enable-api
      -m models/nlu-20210124-181133.tar.gz