version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.2.6-full
    ports:
      - 5005:5005
    volumes:
      - ./rasa:/app
    command: >
      run
      --enable-api
      -m models/nlu-20210124-181133.tar.gz
  mmcc:
    image: giubots/mmcc:latest
    ports:
      - 8765:8765
    volumes:
      - ./config:/usr/src/mmcc/config


    
  